name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.7.21379.14
    - name: Update .NET MAUI manifests
      run: dotnet workload update --from-rollback-file workload.json --verbosity diag
    - name: Install .NET MAUI
      run: dotnet workload install maui --skip-manifest-update --verbosity diag
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
